{
    'name': 'Advance Fuel Station Management System',
    'version': '17.0.0.0.0',
    'summary': 'A complete fuel station management system offering real-time dashboards, sales processing, inventory tracking, shift operations, and financial settlements.',
    'sequence': 1,
    'images': ['static/description/banner.gif'],
    'description': """Fuel Station Management Software powered by advanced fuel software and reliable fuel
                    management software helps automate operations and improve accuracy for fuel station
                    owners. With a smart fuel dashboard, the fuel dashboard provides real-time insights into sales,
                    inventory, and performance. Integrated fleet sales management ensures smooth billing and
                    reporting, while fleet sales management improves control over fleet-based fuel transactions.""",
    'author': "AppsComp Widgets Pvt Ltd",
    'website': "www.appscomp.com",
    'license': 'OPL-1',
    'depends': ['base', 'web', 'hr', 'stock', 'sale', 'account', 'product', 'sale_loyalty', 'purchase', 'contacts',
                'fuel_station_loyalty'],
    'data': [
        'security/fuel_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'reports/meter_reading_report_template.xml',
        'reports/shift_wise_report.xml',
        'reports/customer_outstanding_report.xml',
        'reports/report_payment_mode_template.xml',
        'views/fuel_sales.xml',
        'views/res_config.xml',
        'views/product_template.xml',
        'views/hr_employee.xml',
        'views/closing_entry.xml',
        'views/account.xml',
        'views/fuel_pricing.xml',
        'views/pump.xml',
        'views/nozzle.xml',
        'views/tank.xml',
        'views/shift.xml',
        'views/shift_manager.xml',
        'views/credit_sale.xml',
        'views/cash_settlement.xml',
        'views/menu_actions.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'fuel_station/static/src/css/main_screen.css',
            'fuel_station/static/src/js/main_screen.js',
            'fuel_station/static/src/xml/main_screen.xml',
            # 'fuel_station/static/src/css/pump_screen.css',
            # 'fuel_station/static/src/js/pump_screen.js',
            # 'fuel_station/static/src/xml/pump_screen.xml',
            'fuel_station/static/src/css/cash_settlement.css',
            'fuel_station/static/src/js/cash_settlement.js',
            'fuel_station/static/src/xml/cash_settlement.xml',
            'fuel_station/static/src/css/pricing.css',
            'fuel_station/static/src/js/pricing.js',
            'fuel_station/static/src/xml/pricing.xml',
            'fuel_station/static/src/css/user_screen.css',
            'fuel_station/static/src/js/user_screen.js',
            'fuel_station/static/src/xml/user_screen.xml',
            'fuel_station/static/src/css/petty_cash.css',
            'fuel_station/static/src/js/petty_cash.js',
            'fuel_station/static/src/xml/petty_cash.xml',
            'fuel_station/static/src/css/meter_reading.css',
            'fuel_station/static/src/js/meter_reading.js',
            'fuel_station/static/src/xml/meter_reading.xml',
            'fuel_station/static/src/css/shift_report.css',
            'fuel_station/static/src/js/shift_report.js',
            'fuel_station/static/src/xml/shift_report.xml',
            'fuel_station/static/src/css/customer_outstanding.css',
            'fuel_station/static/src/js/customer_outstanding.js',
            'fuel_station/static/src/xml/customer_outstanding.xml',
            'fuel_station/static/src/css/payment_mode_report.css',
            'fuel_station/static/src/js/payment_mode_report.js',
            'fuel_station/static/src/xml/payment_mode_report.xml',
        ],
    },
    'demo': [],
    'qweb': [],
    'price': '650',
    'currency': 'EUR',
    'installable': True,
    'application': True,
    'auto_install': False,
}
